## Configuration for the

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2

# SAMPLE_SHEET: /workdir/dwm269/scMuscle2/test_metadata.csv #test sample sheet
SAMPLE_SHEET: /workdir/dwm269/scMuscle2/scMuscle2_metadata_v1-0.csv

# Parallelization parameter(s)
THREADS: 10 # how many threads to use for parallel-fastq-dump (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

########################################################################################################
# Important directory file paths
########################################################################################################
TMPDIR: /workdir/dwm269/scMuscle2/tmp # directory for temporary files
PRODIR: /workdir/dwm269/scMuscle2 # Project directory

########################################################################################################
# Executables - file paths
########################################################################################################
PREFETCH: prefetch
PFD: parallel-fastq-dump
