########################################################################################################
# bldrefs_snake
#   Snakemake workflow to generate STAR-compatible reference genomes
#   v1.0
#   Written by David McKellar
#   Last edited: --/--/--, DWM
########################################################################################################

import pandas as pd
import itertools

########################################################################################################
# Config file
########################################################################################################
configfile:'config.yaml'

########################################################################################################
# Directories and locations
########################################################################################################
TMPDIR = config['TMPDIR']
OUTDIR = config['OUTDIR']

shell("mkdir -p {TMPDIR}")
shell("mkdir -p {OUTDIR}")

########################################################################################################
# Variables and references
########################################################################################################

# Get SRR IDs
SRR = list(pd.read_csv(config['SAMPLE_SHEET'], na_filter=False)['SRR.accession'])

########################################################################################################
# Executables
########################################################################################################
PREFETCH = config["PREFETCH"]
PFD = config["PFD"]

########################################################################################################
########################################################################################################
rule all:
    input:
        expand('{OUTDIR}/{sample}', OUTDIR=config['OUTDIR'], sample=SRR) # R1 fastq
#############################################
## fetch genomes
#############################################
rule fetch_genomes:
    output:

    params:
        TMPDIR=TMPDIR
    shell:
        """

        """

#############################################
## generate reference(s)
#############################################
rule configure_STAR_ref:
    input:

    output:

    params:
        TMPDIR=TMPDIR
    threads:
        config["THREADS"]
    shell:
        """
        #TODO: script to generate STAR ref w/ fasta, gtf
        """

rule configure_kallisto_standard_ref:
    input:

    output:

    params:
        TMPDIR=TMPDIR
    threads:
        config["THREADS"]
    shell:
        """

        """
