## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################
#TODO: re-write sample sheet formatting, parsing, etc.
# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ sample sheets ~~~~~
SAMPLE_SHEET: /workdir/dwm269/scMuscle2/scMuscle2_metadata_v1-0.csv


# STARsolo parameters
CORES_HI: 36 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j  {numTotalCores}")
CORES_LO: 8
MEMLIMIT: 99999999999 # limit in bytes

## Cell Barcode white lists
#TODO- move to chemistry sheet
CHEMISTRY_SHEET: resources/chemistry_sheet.csv

########################################################################################################
# Important directory file paths
########################################################################################################
PRODIR: /workdir/dwm269/scMuscle2 # PROject DIRectory
TMPDIR: /workdir/dwm269/scMuscle2/tmp # DIRectory for TeMPorary files
METADIR: /workdir/dwm269/scMuscle2/metadata_ffq # METAdata DIRectory
DATADIR: /workdir/dwm269/scMuscle2/data # Directory for bigger data files (fastq's, STAR outputs, etc)
REFDIR: /workdir/dwm269/scMuscle2/refs # Dir for references from each species

########################################################################################################
# Executables - file paths
########################################################################################################
# Paths to tools used in the pipeline
#TODO - add umi_tools, etc

FFQ_EXEC: ffq
PREFETCH_EXEC: prefetch
PFD_EXEC: parallel-fastq-dump
BAM2FQ_EXEC: ~/usr/bin/bamtofastq_1.4.1

STAR_EXEC: STAR #v2.7.10a
FASTQC_EXEC: fastqc
GGET_EXEC: gget
TRIMGALORE_EXEC: trim_galore
CUTADAPT_EXEC: cutadapt
# BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
# FASTX_COLLAPSER: fastx_collapser
# BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
# PICARD_EXEC: /home/dwm269/miniconda3/envs/STARsolo/share/picard-2.26.10-0/picard.jar
