## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################
#TODO: re-write sample sheet formatting, parsing, etc.
# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ sample sheets ~~~~~
SAMPLE_SHEET: ../scMuscle2_metadata_v1-0.csv


# STARsolo parameters
CORES_HI: 4 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j  {numTotalCores}")
CORES_MID: 2
CORES_LO: 1

MEMLIMIT_HI: 100000000 # Number of bytes to use per core -252657461480
MEMLIMIT_LO: 8G

#195000000000 # limit in bytes - 195gb

## Chemistry details (whitelists, barcode/UMI design, etc.)
CHEMISTRY_SHEET: resources/chemistry_sheet.csv
FASTQC_ADAPTERS: resources/fastqc_adapters.txt

########################################################################################################
# Important directory file paths
########################################################################################################
PRODIR: /gpfs/commons/groups/innovation/dwm/scMuscle2 # PROject DIRectory

########################################################################################################
# Executables - file paths
########################################################################################################
# Paths to tools used in the pipeline
#TODO - add missing tools

EXEC:
  PREFETCH: ~/sratoolkit.3.0.10-centos_linux64/bin/prefetch.3.0.10
  FASTERQDUMP: ~/sratoolkit.3.0.10-centos_linux64/bin/fasterq-dump.3.0.10
  FASTQDL: fastq-dl
  BAM2FQ: ~/bamtofastq_linux #v1.4.1
  CUTADAPT: cutadapt #v4.1
  FASTQC: fastqc #v0.11.9
  FFQ: ffq
  GGET: gget #v0.2.6
  MULTIQC: mutliqc
  PIGZ: pigz
  QUALIMAP: qualimap #v
  SAMTOOLS: samtools #samtools #v1.3.1 (just used for indexing .bam files)
  STAR: STAR #v2.7.10a
  TRIMGALORE: trim_galore
  UMITOOLS: umi_tools #v

## Deprecated
# PFD: parallel-fastq-dump
# BAM2SPLITBW: ~/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
# FASTX_COLLAPSER: fastx_collapser
# BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
# PICARD: ~/miniconda3/envs/STARsolo/share/picard-2.26.10-0/picard.jar
